/* authentication */
//login
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
//register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";
//auth get
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
//auth logout
export const AUTH_LOGOUT = "AUTH_LOGOUT";
/* angkeiteu */
//angkeiteu post
export const ANGKEITEU_POST = "ANGKEITEU_POST";
export const ANGKEITEU_POST_SUCCESS = "ANGKEITEU_POST_SUCCESS";
export const ANGKEITEU_POST_FAILURE = "ANGKEITEU_POST_FAILURE";
//angkeiteu list
export const ANGKEITEU_LIST = "ANGKEITEU_LIST";
export const ANGKEITEU_LIST_SUCCESS = "ANGKEITEU_LIST_SUCCESS";
export const ANGKEITEU_LIST_FAILURE = "ANGKEITEU_LIST_FAILURE";
//angkeiteu get
export const ANGKEITEU_GET = "ANGKEITEU_GET";
export const ANGKEITEU_GET_SUCCESS = "ANGKEITEU_GET_SUCCESS"
export const ANGKEITEU_GET_FAILURE = "ANGKEITEU_GET_FAILURE";
//angkeiteu participate
export const ANGKEITEU_PARTICIPATE = "ANGKEITEU_PARTICIPATE";
export const ANGKEITEU_PARTICIPATE_SUCCESS = "ANGKEITEU_PARTICIPATE_SUCCESS";
export const ANGKEITEU_PARTICIPATE_FAILURE = "ANGKEITEU_PARTICIPATE_FAILURE";
//angkeiteu search
export const ANGKEITEU_SEARCH = "ANGKEITEU_SEARCH";
export const ANGKEITEU_SEARCH_SUCCESS = "ANGKEITEU_SEARCH_SUCCESS";
export const ANGKEITEU_SEARCH_FAILURE = "ANGKEITEU_SEARCH_FAILURE";
/* comment */
//comment post
export const COMMENT_POST = "COMMENT_POST";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE";
//comment list
export const COMMENT_LIST = "COMMENT_LIST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAILURE = "COMMENT_LIST_FAILURE";
//comment recommend
export const COMMENT_RECOMMEND = "COMMENT_RECOMMEND";
export const COMMENT_RECOMMEND_SUCCESS = "COMMENT_RECOMMEND_SUCCESS";
export const COMMENT_RECOMMEND_FAILURE = "COMMENT_RECOMMEND_FAILURE";
//comment count
export const COMMENT_COUNT = "COMMENT_COUNT";
export const COMMENT_COUNT_SUCCESS = "COMMENT_COUNT_SUCCESS";
export const COMMENT_COUNT_FAILURE = "COMMENT_COUNT_FAILURE";
/* file */
//image file upload
export const IMAGE_FILE_UPLOAD = "IMAGE_FILE_UPLOAD";
export const IMAGE_FILE_UPLOAD_SUCCESS = "IMAGE_FILE_UPLOAD_SUCCESS";
export const IMAGE_FILE_UPLOAD_FAILURE = "IMAGE_FILE_UPLOAD_FAILURE";
//file info get
export const IMAGE_FILE_GET = "IMAGE_FILE_GET";
export const IMAGE_FILE_GET_SUCCESS = "IMAGE_FILE_GET_SUCCESS";
export const IMAGE_FILE_GET_FAILURE = "IMAGE_FILE_GET_FAILURE";

/* chart filter */
export const CHART_FILTER_CONDITION_ADD = "CHART_FILTER_CONDITION_ADD";
export const CHART_FILTER_CONDITION_REMOVE = "CHART_FILTER_CONDITION_REMOVE";

/* angkeiteu explorer */
export const ANGKEITEU_EXPLORER_ANGKEITEU_SELECT = "ANGKEITEU_EXPLORER_ANGKEITEU_SELECT";
export const ANGKEITEU_EXPLORER_ANGKEITEU_UNSELECT = "ANGKEITEU_EXPLORER_ANGKEITEU_UNSELECT";

/* front view interaction */
export const OPEN_SEARCH_VIEW = "OPEN_SEARCH_VIEW";
export const CLOSE_SEARCH_VIEW = "CLOSE_SEARCH_VIEW";
export const ENTER_KEYWORD = "ENTER_KEYWORD";
