/* authentication */
//login
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
//register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";
//auth get
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
//auth logout
export const AUTH_LOGOUT = "AUTH_LOGOUT";
/* angkeiteu */
//angkeiteu post
export const ANGKEITEU_POST = "ANGKEITEU_POST";
export const ANGKEITEU_POST_SUCCESS = "ANGKEITEU_POST_SUCCESS";
export const ANGKEITEU_POST_FAILURE = "ANGKEITEU_POST_FAILURE";
//angkeiteu list
export const ANGKEITEU_LIST = "ANGKEITEU_LIST";
export const ANGKEITEU_LIST_SUCCESS = "ANGKEITEU_LIST_SUCCESS";
export const ANGKEITEU_LIST_FAILURE = "ANGKEITEU_LIST_FAILURE";
//angkeiteu get
export const ANGKEITEU_GET = "ANGKEITEU_GET";
export const ANGKEITEU_GET_SUCCESS = "ANGKEITEU_GET_SUCCESS"
export const ANGKEITEU_GET_FAILURE = "ANGKEITEU_GET_FAILURE";
//angkeiteu participate
export const ANGKEITEU_PARTICIPATE = "ANGKEITEU_PARTICIPATE";
export const ANGKEITEU_PARTICIPATE_SUCCESS = "ANGKEITEU_PARTICIPATE_SUCCESS";
export const ANGKEITEU_PARTICIPATE_FAILURE = "ANGKEITEU_PARTICIPATE_FAILURE";
//angkeiteu search
export const ANGKEITEU_SEARCH = "ANGKEITEU_SEARCH";
export const ANGKEITEU_SEARCH_SUCCESS = "ANGKEITEU_SEARCH_SUCCESS";
export const ANGKEITEU_SEARCH_FAILURE = "ANGKEITEU_SEARCH_FAILURE";
/* comment */
//comment post
export const COMMENT_POST = "COMMENT_POST";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE";
//comment list
export const COMMENT_LIST = "COMMENT_LIST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAILURE = "COMMENT_LIST_FAILURE";

/* front view interaction */
export const OPEN_SEARCH_VIEW = "OPEN_SEARCH_VIEW";
export const CLOSE_SEARCH_VIEW = "CLOSE_SEARCH_VIEW";
export const ENTER_KEYWORD = "ENTER_KEYWORD";
